<?php

namespace Database\Seeders;

use App\Enums\AccessType;
use App\Enums\CourseLevel;
use App\Models\Article;
use App\Models\Assignment;
use App\Models\Course;
use App\Models\CourseCategory;
use App\Models\CourseContent;
use App\Models\CourseSyllabus;
use App\Models\Quiz;
use App\Models\QuizChoice;
use App\Models\QuizQuestion;
use App\Models\User;
use App\Models\Video;
use Illuminate\Database\Seeder;

/**
 * CourseContentSeeder
 *
 * Seeder khusus untuk membuat course dengan silabus dan konten lengkap.
 * Course yang dibuat memiliki prefix "[LENGKAP]" untuk membedakannya
 * dari course dummy yang hanya untuk display data.
 *
 * Fitur:
 * - 2 Course khusus dengan data realistis
 * - 3 Silabus per course dengan topik terstruktur
 * - 4 Content per silabus (video, article, quiz, assignment)
 * - Konten yang spesifik dan relevan dengan topik
 *
 * Usage:
 * php artisan db:seed --class=CourseContentSeeder
 *
 * @author Generated by AI Assistant
 *
 * @version 2.0 - Integrated with DatabaseSeeder
 */
class CourseContentSeeder extends Seeder
{
    /**
     * Prefix untuk course yang memiliki silabus lengkap
     */
    public const SPECIAL_COURSE_PREFIX = '[LENGKAP]';

    /**
     * Get courses yang memiliki silabus lengkap
     */
    public static function getSpecialCourses()
    {
        return Course::where('title', 'LIKE', self::SPECIAL_COURSE_PREFIX.'%');
    }

    /**
     * Check if course is a special course with full syllabus
     */
    public static function isSpecialCourse(Course $course): bool
    {
        return str_starts_with($course->title, self::SPECIAL_COURSE_PREFIX);
    }

    /**
     * Get example usage for special courses
     */
    public static function getUsageExamples(): array
    {
        return [
            'Get all special courses' => 'CourseContentSeeder::getSpecialCourses()->get()',
            'Check if course is special' => 'CourseContentSeeder::isSpecialCourse($course)',
            'Get special courses with syllabi' => 'CourseContentSeeder::getSpecialCourses()->with("syllabus")->get()',
            'Count special courses' => 'CourseContentSeeder::getSpecialCourses()->count()',
            'Get prefix constant' => 'CourseContentSeeder::SPECIAL_COURSE_PREFIX',
        ];
    }

    /**
     * Run the database seeds.
     *
     * Seeder ini membuat course khusus yang dilengkapi dengan:
     * - Silabus terstruktur (3 modul per course)
     * - Course content lengkap (video, article, quiz, assignment per modul)
     * - Data realistis dan profesional
     *
     * Course ini dibedakan dengan prefix "[LENGKAP]" untuk memudahkan identifikasi
     * dari course dummy lainnya yang hanya untuk display data.
     */
    public function run(): void
    {
        // Set a default user for created_by and modified_by
        $user = User::first();
        if (! $user) {
            $user = User::create([
                'username' => 'admin',
                'email' => 'admin@example.com',
                'password' => bcrypt('password'),
                'id_number' => '00000',
                'phone_number' => '081234567890',
            ]);
        }

        // Ensure we have a course category
        $courseCategory = CourseCategory::first();
        if (! $courseCategory) {
            $courseCategory = CourseCategory::create([
                'name' => 'Programming',
                'slug' => 'programming',
            ]);
        }

        // Get or create a teacher
        $teacher = User::role('instructor')->first();
        if (! $teacher) {
            $teacher = $user; // Use the admin user if no instructor exists
        }

        // Create 2 courses with realistic data
        $courses = [];

        // Course data yang lebih realistis berdasarkan factory
        // Menambahkan prefix khusus agar mudah diidentifikasi sebagai course dengan silabus lengkap
        $courseData = [
            [
                'title' => '[LENGKAP] Web Development Komprehensif',
                'slug' => 'lengkap-web-development-komprehensif',
                'description' => $this->generateJoditContent('Web Development'),
                'short_desc' => 'Pelajari skill web development dari dasar hingga advanced dengan metode pembelajaran praktis dan project-based learning. Course ini dilengkapi dengan silabus lengkap dan materi terstruktur.',
                'level' => CourseLevel::BEGINNER,
                'access_type' => AccessType::FREE,
                'price' => 0,
                'duration' => 45,
                'thumbnail' => $this->getSampleThumbnail(),
            ],
            [
                'title' => '[LENGKAP] Data Science Praktis',
                'slug' => 'lengkap-data-science-praktis',
                'description' => $this->generateJoditContent('Data Science'),
                'short_desc' => 'Kursus data science komprehensif dengan Python, machine learning, dan real-world case studies untuk professional development. Course dengan struktur pembelajaran lengkap.',
                'level' => CourseLevel::INTERMEDIATE,
                'access_type' => AccessType::PAID,
                'price' => 750000,
                'duration' => 80,
                'thumbnail' => $this->getSampleThumbnail(),
            ],
        ];

        for ($i = 0; $i < 2; $i++) {
            $data = $courseData[$i];

            $course = Course::create([
                'title' => $data['title'],
                'slug' => $data['slug'],
                'teacher_id' => $teacher->id,
                'program_id' => null,
                'course_category_id' => $courseCategory->id,
                'description' => $data['description'],
                'short_desc' => $data['short_desc'],
                'thumbnail' => $data['thumbnail'],
                'access_type' => $data['access_type'],
                'price' => $data['price'],
                'level' => $data['level'],
                'duration' => $data['duration'],
                'extra_description' => "⭐ COURSE LENGKAP dengan silabus terstruktur! ⭐\n\nKursus ini dilengkapi dengan:\n• 3 Modul pembelajaran bertahap\n• Video pembelajaran HD berkualitas tinggi\n• Materi bacaan lengkap dan mudah dipahami\n• Quiz interaktif untuk mengukur pemahaman\n• Assignment praktis dengan studi kasus nyata\n• Struktur pembelajaran yang sistematis dan teruji\n\nCourse ini berbeda dari course display lainnya karena memiliki konten pembelajaran yang lengkap dan siap untuk pembelajaran yang sesungguhnya.",
                'is_published' => true,
                'created_by' => $user->username,
                'modified_by' => $user->username,
            ]);

            $courses[] = $course;

            // Create 2 syllabus for each course
            for ($j = 1; $j <= 2; $j++) {
                $syllabus = CourseSyllabus::create([
                    'course_id' => $course->id,
                    'title' => "Modul {$j} - ".$this->getSyllabusTitle($course->title, $j),
                    'description' => $this->getSyllabusDescription($course->title, $j),
                    'order' => $j,
                    'is_completed' => false,
                    'created_by' => $user->username,
                    'modified_by' => $user->username,
                ]);

                // Create 4 contents for each syllabus (1 per type)
                $contentTypes = ['video', 'article', 'quiz', 'assignment'];

                foreach ($contentTypes as $index => $type) {
                    $contentOrder = $index + 1;

                    $courseContent = CourseContent::create([
                        'course_id' => $course->id,
                        'course_syllabus_id' => $syllabus->id,
                        'title' => $this->getContentTitle($type, $course->title, $j, $contentOrder),
                        'order' => $contentOrder,
                        'type' => $type,
                        'is_free_preview' => $contentOrder === 1, // First content is free preview
                        'created_by' => $user->username,
                        'modified_by' => $user->username,
                    ]);

                    // Create related content based on type
                    $this->createRelatedContent($courseContent, $type);
                }
            }

            // Recalculate global order for the course
            CourseContent::recalculateGlobalOrder($course->id);
        }

        $this->command->info('Course content seeder completed!');
        $this->command->info('Created '.count($courses)." special courses with '[LENGKAP]' prefix");
        $this->command->info('Each course has 2 detailed modules with 4 contents per module');
        $this->command->info('Total: '.(count($courses) * 2).' syllabi and '.(count($courses) * 2 * 4).' course contents');
        $this->command->info('Quiz includes 3 questions with multiple choices, Assignment has detailed instructions');
        $this->command->info('These courses are separate from the '.Course::where('title', 'NOT LIKE', '[LENGKAP]%')->count().' dummy courses for display purposes');
    }

    /**
     * Create related content based on course content type
     */
    private function createRelatedContent(CourseContent $courseContent, string $type): void
    {
        switch ($type) {
            case 'video':
                Video::create([
                    'course_content_id' => $courseContent->id,
                    'video_url' => 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                    'short_description' => "Video pembelajaran untuk {$courseContent->title}",
                ]);
                break;

            case 'article':
                Article::create([
                    'course_content_id' => $courseContent->id,
                    'body' => $this->generateArticleContent($courseContent->title),
                    'video_url' => null,
                ]);
                break;

            case 'quiz':
                $quiz = Quiz::create([
                    'course_content_id' => $courseContent->id,
                    'description' => "Quiz untuk menguji pemahaman materi {$courseContent->title}",
                    'number_of_questions' => 3,
                    'duration' => 15,
                    'created_by' => $courseContent->created_by,
                    'modified_by' => $courseContent->modified_by,
                ]);

                // Create quiz questions with choices
                $this->createQuizQuestions($quiz, $courseContent);
                break;

            case 'assignment':
                Assignment::create([
                    'course_content_id' => $courseContent->id,
                    'instruction' => $this->generateAssignmentInstruction($courseContent->title),
                    'due_date' => now()->addDays(7),
                ]);
                break;
        }
    }

    /**
     * Create quiz questions with multiple choices
     */
    private function createQuizQuestions(Quiz $quiz, CourseContent $courseContent): void
    {
        $questions = $this->getQuizQuestions($courseContent->title);

        foreach ($questions as $index => $questionData) {
            $question = QuizQuestion::create([
                'quiz_id' => $quiz->id,
                'question' => $questionData['question'],
                'question_type' => 'multiple_choice',
                'score' => 1, // Fixed: setiap question 1 point
                'order' => $index + 1,
                'created_by' => $quiz->created_by,
                'modified_by' => $quiz->modified_by,
            ]);

            // Create choices for each question
            foreach ($questionData['choices'] as $choiceIndex => $choice) {
                QuizChoice::create([
                    'question_id' => $question->id,
                    'answer_option' => $choice['text'],
                    'is_correct' => $choice['is_correct'],
                    'created_by' => $quiz->created_by,
                    'modified_by' => $quiz->modified_by,
                ]);
            }
        }
    }

    /**
     * Get quiz questions based on content title
     */
    private function getQuizQuestions(string $contentTitle): array
    {
        if (str_contains(strtolower($contentTitle), 'html')) {
            return [
                [
                    'question' => 'Apa fungsi utama dari tag <div> dalam HTML?',
                    'choices' => [
                        ['text' => 'Membuat tabel', 'is_correct' => false],
                        ['text' => 'Container untuk mengelompokkan elemen', 'is_correct' => true],
                        ['text' => 'Menambahkan gambar', 'is_correct' => false],
                        ['text' => 'Membuat form', 'is_correct' => false],
                    ],
                ],
                [
                    'question' => 'Tag mana yang digunakan untuk membuat heading utama?',
                    'choices' => [
                        ['text' => '<h1>', 'is_correct' => true],
                        ['text' => '<header>', 'is_correct' => false],
                        ['text' => '<title>', 'is_correct' => false],
                        ['text' => '<main>', 'is_correct' => false],
                    ],
                ],
                [
                    'question' => 'Atribut mana yang digunakan untuk menambahkan CSS class?',
                    'choices' => [
                        ['text' => 'id', 'is_correct' => false],
                        ['text' => 'class', 'is_correct' => true],
                        ['text' => 'style', 'is_correct' => false],
                        ['text' => 'name', 'is_correct' => false],
                    ],
                ],
            ];
        } elseif (str_contains(strtolower($contentTitle), 'python')) {
            return [
                [
                    'question' => 'Tipe data mana yang digunakan untuk menyimpan daftar item dalam Python?',
                    'choices' => [
                        ['text' => 'string', 'is_correct' => false],
                        ['text' => 'integer', 'is_correct' => false],
                        ['text' => 'list', 'is_correct' => true],
                        ['text' => 'boolean', 'is_correct' => false],
                    ],
                ],
                [
                    'question' => 'Library mana yang paling umum digunakan untuk data analysis di Python?',
                    'choices' => [
                        ['text' => 'pandas', 'is_correct' => true],
                        ['text' => 'requests', 'is_correct' => false],
                        ['text' => 'django', 'is_correct' => false],
                        ['text' => 'flask', 'is_correct' => false],
                    ],
                ],
                [
                    'question' => 'Fungsi mana yang digunakan untuk mencetak output di Python?',
                    'choices' => [
                        ['text' => 'console.log()', 'is_correct' => false],
                        ['text' => 'print()', 'is_correct' => true],
                        ['text' => 'echo()', 'is_correct' => false],
                        ['text' => 'output()', 'is_correct' => false],
                    ],
                ],
            ];
        } else {
            // Default general questions
            return [
                [
                    'question' => 'Apa yang dimaksud dengan algoritma dalam pemrograman?',
                    'choices' => [
                        ['text' => 'Bahasa pemrograman', 'is_correct' => false],
                        ['text' => 'Langkah-langkah sistematis untuk menyelesaikan masalah', 'is_correct' => true],
                        ['text' => 'Software untuk coding', 'is_correct' => false],
                        ['text' => 'Database sistem', 'is_correct' => false],
                    ],
                ],
                [
                    'question' => 'Apa kepanjangan dari API?',
                    'choices' => [
                        ['text' => 'Application Programming Interface', 'is_correct' => true],
                        ['text' => 'Advanced Programming Integration', 'is_correct' => false],
                        ['text' => 'Automated Process Interface', 'is_correct' => false],
                        ['text' => 'Application Process Integration', 'is_correct' => false],
                    ],
                ],
                [
                    'question' => 'Apa fungsi utama dari version control system seperti Git?',
                    'choices' => [
                        ['text' => 'Menjalankan program', 'is_correct' => false],
                        ['text' => 'Melacak perubahan kode dan kolaborasi', 'is_correct' => true],
                        ['text' => 'Membuat database', 'is_correct' => false],
                        ['text' => 'Testing aplikasi', 'is_correct' => false],
                    ],
                ],
            ];
        }
    }

    /**
     * Generate assignment instruction based on content title
     */
    private function generateAssignmentInstruction(string $contentTitle): string
    {
        if (str_contains(strtolower($contentTitle), 'html') || str_contains(strtolower($contentTitle), 'landing page')) {
            return "**Tugas: Membuat Landing Page Sederhana**\n\n**Objektif:**\nMembuat halaman web landing page yang responsive dan menarik\n\n**Instruksi:**\n1. Buat file HTML dengan struktur semantic yang benar\n2. Implementasikan CSS untuk styling yang menarik\n3. Tambahkan JavaScript untuk interaktivitas dasar\n4. Pastikan website responsive di berbagai ukuran layar\n\n**Requirement:**\n- Header dengan navigasi\n- Hero section dengan call-to-action\n- Section fitur/layanan\n- Footer dengan informasi kontak\n\n**Submission:**\n- Upload file HTML, CSS, dan JS\n- Sertakan screenshot tampilan desktop dan mobile\n- Tulis dokumentasi singkat tentang proses pembuatan\n\n**Deadline:** 7 hari dari tanggal assignment\n**Format:** ZIP file dengan nama: nama_anda_landing_page.zip";
        } elseif (str_contains(strtolower($contentTitle), 'data') || str_contains(strtolower($contentTitle), 'python')) {
            return "**Tugas: Analisis Dataset Real**\n\n**Objektif:**\nMelakukan exploratory data analysis (EDA) pada dataset yang disediakan\n\n**Instruksi:**\n1. Download dataset yang disediakan di platform\n2. Load data menggunakan pandas\n3. Lakukan data cleaning dan preprocessing\n4. Buat visualisasi yang informatif\n5. Berikan insights dari analisis yang dilakukan\n\n**Deliverables:**\n- Jupyter notebook dengan analisis lengkap\n- Data cleaning steps yang jelas\n- Minimal 5 visualisasi berbeda\n- Summary insights dan rekomendasi\n\n**Tools yang harus digunakan:**\n- Python dengan pandas, matplotlib, seaborn\n- Jupyter Notebook atau Google Colab\n\n**Submission:**\n- File .ipynb (Jupyter notebook)\n- File .py jika ada script terpisah\n- PDF export dari notebook\n\n**Deadline:** 7 hari dari tanggal assignment\n**Format:** ZIP file dengan nama: nama_anda_data_analysis.zip";
        } else {
            return "**Tugas Praktik: Implementasi Konsep Pembelajaran**\n\n**Objektif:**\nMenerapkan konsep yang telah dipelajari dalam project praktis\n\n**Instruksi:**\n1. Baca dan pahami materi yang telah diberikan\n2. Identifikasi konsep utama yang akan diimplementasikan\n3. Buat project sederhana yang mendemonstrasikan pemahaman Anda\n4. Dokumentasikan proses dan hasil yang dicapai\n\n**Requirement:**\n- Project harus functional dan dapat dijalankan\n- Kode harus rapi dan well-commented\n- Sertakan README dengan penjelasan project\n- Testing basic functionality\n\n**Submission Guidelines:**\n- Source code lengkap\n- Documentation (README.md)\n- Screenshot atau video demo (opsional)\n- Reflection paper singkat tentang pembelajaran\n\n**Deadline:** 7 hari dari tanggal assignment\n**Format:** ZIP file dengan struktur folder yang rapi";
        }
    }

    /**
     * Generate realistic course title
     */
    private function generateCourseTitle(): string
    {
        $topics = [
            'Web Development',
            'Mobile Development',
            'Data Science',
            'Machine Learning',
            'Digital Marketing',
            'UI/UX Design',
            'Database Management',
            'Cloud Computing',
            'Cybersecurity',
            'DevOps',
            'Artificial Intelligence',
            'Blockchain',
            'Python Programming',
            'JavaScript Fundamentals',
            'React Development',
        ];

        $levels = ['Dasar', 'Lanjutan', 'Mahir', 'Profesional', 'Komprehensif'];
        $formats = ['Praktis', 'Lengkap', 'Intensif', 'Mudah Dipahami'];

        $topic = fake()->randomElement($topics);
        $modifier = fake()->randomElement(array_merge($levels, $formats));

        return "{$topic} {$modifier}";
    }

    /**
     * Generate realistic Jodit editor content
     */
    private function generateJoditContent(string $topic): string
    {
        $paragraphs = [
            "<p>Selamat datang di kursus <strong>{$topic}</strong> yang akan mengubah karir Anda! Kursus ini dirancang khusus untuk memberikan pemahaman mendalam tentang teknologi terkini dengan pendekatan praktis dan mudah dipahami.</p>",

            "<p><strong>Apa yang akan Anda pelajari:</strong></p>
            <ul>
                <li>Konsep fundamental dan teori dasar {$topic}</li>
                <li>Implementasi praktis dengan studi kasus nyata</li>
                <li>Best practices dan industry standards terkini</li>
                <li>Tips dan trik dari para ahli di bidang {$topic}</li>
                <li>Tools dan teknologi yang digunakan profesional</li>
            </ul>",

            "<p><em>Kursus ini cocok untuk:</em></p>
            <ol>
                <li>Pemula yang ingin memulai karir di bidang {$topic}</li>
                <li>Profesional yang ingin meningkatkan skill</li>
                <li>Mahasiswa yang mencari pengetahuan praktis</li>
                <li>Entrepreneur yang ingin memahami teknologi</li>
            </ol>",

            "<blockquote>
                <p>\"Investasi terbaik adalah investasi pada pengetahuan dan keterampilan diri sendiri. Kursus {$topic} ini akan memberikan Anda foundation yang kuat untuk berkembang di era digital.\"</p>
            </blockquote>",

            '<p>Dengan materi yang <strong>terstruktur</strong> dan <em>up-to-date</em>, Anda akan mendapatkan pembelajaran yang komprehensif. Setiap modul dilengkapi dengan:</p>
            <ul>
                <li>Video pembelajaran berkualitas tinggi dengan subtitle</li>
                <li>Materi bacaan lengkap dan mudah dipahami</li>
                <li>Quiz interaktif untuk mengukur pemahaman</li>
                <li>Assignment praktis dengan feedback personal</li>
                <li>Forum diskusi dengan instruktur dan peserta lain</li>
                <li>Sertifikat completion yang diakui industri</li>
            </ul>',

            "<p>Jangan lewatkan kesempatan untuk meningkatkan kemampuan Anda di bidang {$topic}. Daftar sekarang dan mulai perjalanan pembelajaran yang mengubah hidup!</p>",
        ];

        // Pilih 4-6 paragraf secara acak
        $selectedParagraphs = fake()->randomElements($paragraphs, fake()->numberBetween(4, 6));

        return implode("\n\n", $selectedParagraphs);
    }

    /**
     * Get sample thumbnail path
     */
    private function getSampleThumbnail(): ?string
    {
        $samplesPath = public_path('assets/images/samples');

        // Check if samples directory exists
        if (! is_dir($samplesPath)) {
            return null; // Return null if no samples directory
        }

        $imageExtensions = ['jpg', 'jpeg', 'png', 'webp'];
        $sampleImages = [];

        // Get all image files from samples directory
        foreach (scandir($samplesPath) as $file) {
            if ($file === '.' || $file === '..') {
                continue;
            }

            $extension = strtolower(pathinfo($file, PATHINFO_EXTENSION));
            if (in_array($extension, $imageExtensions)) {
                $sampleImages[] = $file;
            }
        }

        // Return null if no sample images found
        if (empty($sampleImages)) {
            return null;
        }

        // Return random sample image path
        $randomImage = fake()->randomElement($sampleImages);

        return 'assets/images/samples/'.$randomImage;
    }

    /**
     * Get content title based on type, course, module and order
     */
    private function getContentTitle(string $type, string $courseTitle, int $moduleNumber, int $contentOrder): string
    {
        $webDevContents = [
            1 => [
                'video' => 'HTML5 Semantic Elements & CSS3 Fundamentals',
                'article' => 'Modern JavaScript ES6+ Features',
                'quiz' => 'Quiz: Frontend Fundamentals',
                'assignment' => 'Tugas: Membuat Landing Page Responsive',
            ],
            2 => [
                'video' => 'React.js Components & State Management',
                'article' => 'Building RESTful APIs dengan Node.js',
                'quiz' => 'Quiz: Full Stack Development',
                'assignment' => 'Tugas: Aplikasi Web Full Stack',
            ],
        ];

        $dataScienceContents = [
            1 => [
                'video' => 'Python Environment Setup & Pandas Basics',
                'article' => 'Data Cleaning & Exploratory Analysis',
                'quiz' => 'Quiz: Python & Data Manipulation',
                'assignment' => 'Tugas: Analisis Dataset Real',
            ],
            2 => [
                'video' => 'Machine Learning dengan Scikit-learn',
                'article' => 'Data Visualization & Statistical Insights',
                'quiz' => 'Quiz: ML Algorithms & Visualization',
                'assignment' => 'Tugas: Predictive Analytics Project',
            ],
        ];

        if (str_contains(strtolower($courseTitle), 'web development')) {
            return $webDevContents[$moduleNumber][$type] ?? ucfirst($type)." - Modul {$moduleNumber}";
        } elseif (str_contains(strtolower($courseTitle), 'data science')) {
            return $dataScienceContents[$moduleNumber][$type] ?? ucfirst($type)." - Modul {$moduleNumber}";
        }

        // Default fallback
        return ucfirst($type)." - Modul {$moduleNumber}.{$contentOrder}";
    }

    /**
     * Get syllabus title based on course and module number
     */
    private function getSyllabusTitle(string $courseTitle, int $moduleNumber): string
    {
        $webDevModules = [
            1 => 'Frontend Fundamentals & Interactive Design',
            2 => 'Backend Development & Full Stack Integration',
        ];

        $dataScienceModules = [
            1 => 'Python Fundamentals & Data Analysis',
            2 => 'Machine Learning & Data Visualization',
        ];

        if (str_contains(strtolower($courseTitle), 'web development')) {
            return $webDevModules[$moduleNumber];
        } elseif (str_contains(strtolower($courseTitle), 'data science')) {
            return $dataScienceModules[$moduleNumber];
        }

        // Default fallback
        return 'Pembelajaran Dasar dan Fundamental';
    }

    /**
     * Get syllabus description based on course and module number
     */
    private function getSyllabusDescription(string $courseTitle, int $moduleNumber): string
    {
        $webDevDescriptions = [
            1 => 'Modul ini membahas fundamental pengembangan web modern meliputi HTML5 semantic, CSS3 advanced styling, JavaScript ES6+, dan responsive design. Anda akan menguasai konsep dasar hingga membuat user interface yang interaktif dan mobile-friendly.',
            2 => 'Pelajari pengembangan full-stack dengan framework modern seperti React.js/Vue.js untuk frontend dan Node.js/Express untuk backend. Modul mencakup state management, API integration, database connectivity, dan deployment ke production.',
        ];

        $dataScienceDescriptions = [
            1 => 'Menguasai Python sebagai tool utama data science, library pandas untuk manipulasi data, numpy untuk komputasi numerik, dan matplotlib/seaborn untuk visualisasi. Termasuk exploratory data analysis dan data cleaning techniques.',
            2 => 'Implementasi machine learning menggunakan scikit-learn, dari supervised learning hingga unsupervised learning. Mencakup feature engineering, model evaluation, dan advanced visualization untuk data insights dan predictive analytics.',
        ];

        if (str_contains(strtolower($courseTitle), 'web development')) {
            return $webDevDescriptions[$moduleNumber];
        } elseif (str_contains(strtolower($courseTitle), 'data science')) {
            return $dataScienceDescriptions[$moduleNumber];
        }

        // Default fallback
        return 'Modul pembelajaran komprehensif yang dirancang untuk memberikan pemahaman mendalam tentang topik yang dibahas dengan pendekatan praktis dan teoritis.';
    }

    /**
     * Generate sample article content
     */
    private function generateArticleContent(string $title): string
    {
        return "
# {$title}

## Pendahuluan

Artikel ini akan membahas tentang {$title} secara komprehensif. Materi ini dirancang untuk memberikan pemahaman yang mendalam tentang topik yang dibahas.

## Pembahasan

### Konsep Dasar

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.

### Implementasi

Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

### Best Practices

1. Selalu ikuti standar yang telah ditetapkan
2. Gunakan pendekatan yang sistematis
3. Dokumentasikan setiap langkah yang dilakukan
4. Lakukan testing secara berkala

## Kesimpulan

Materi {$title} merupakan bagian penting dalam pembelajaran ini. Dengan memahami konsep dan implementasinya, diharapkan peserta dapat menerapkan ilmu yang didapat dalam praktik nyata.

## Referensi

- Dokumentasi resmi
- Best practice guidelines
- Community resources
        ";
    }
}
